name: Build and push Docker images

on:
  push:
    branches:
      - master
    paths:
      - '**/DOCKERFILE'
      - '**/*.sh'
      - '**/*.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        folder:
          - BattlefieldVU

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.folder }}
        push: true
        file: ${{ matrix.folder }}/DOCKERFILE
        tags: ghcr.io/whatscs/containers:${{ matrix.folder }}
        labels: ${{ matrix.folder }}
